ElectricTransportBlog/Controllers/PublicationCommentsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ElectricTransportBlog.Core.Constants;
using ElectricTransportBlog.Core.Contracts;
using ElectricTransportBlog.Core.Extensions;
using ElectricTransportBlog.Core.Models.PublicationComments;
using ElectricTransportBlog.Infrastructure.Data;

namespace ElectricTransportBlog.Controllers
{
    public class PublicationCommentsController : Controller
    {
        private readonly IPublicationCommentsService comments;
        private readonly IPublicationService news;
        private readonly IUserService users;

        public PublicationCommentsController(IPublicationCommentsService comments, IPublicationService news, IUserService users)
        {
            this.comments = comments;
            this.news = news;
            this.users = users;
        }

        [Authorize]
        public IActionResult Edit(Guid id)
        {
            var userId = this.users.IdByUser(this.User.Id());

            if (userId == null)
            {
                ViewData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            if (!this.comments.IsByUser(id, userId) && !User.IsInRole(UserConstants.Administrator) && !User.IsInRole(UserConstants.Moderator))
            {
                return BadRequest();
            }

            var commentForm = this.comments.EditViewData(id);

            return View(commentForm);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(Guid id, CommentsEditFormModel comment)
        {
            var userId = this.users.IdByUser(this.User.Id());
            var newsId = this.comments.IdOfPublication(id);

            if (!this.comments.IsByUser(id, userId) && !User.IsInRole(UserConstants.Administrator) && !User.IsInRole(UserConstants.Moderator))
            {
                return BadRequest();
            }

            var edited = this.comments.Edit(
                id,
                comment.Content.Trim(),
                lastEditedOn: DateTime.Now
                );

            if (!edited)
            {
                return BadRequest();
            }

            TempData[MessageConstants.SuccessMessage] = "Коментарът беше успешно редактиран.";

            return Redirect($"../../Publication/Details/{newsId}");
        }

        [Authorize]
        public IActionResult Delete(Guid id)
        {
            var userId = this.users.IdByUser(this.User.Id());
            var newsId = this.comments.IdOfPublication(id);

            if (!this.comments.IsByUser(id, userId) && !User.IsInRole(UserConstants.Administrator) && !User.IsInRole(UserConstants.Moderator))
            {
                return BadRequest();
            }

            var deleted = this.comments.Delete(id);

            if (!deleted)
            {
                return BadRequest();
            }

            TempData[MessageConstants.SuccessMessage] = "Коментарът беше успешно изтрит.";
            return Redirect($"../../Publication/Details/{newsId}");
        }
    }
}

ElectricTransportBlog/Controllers/PublicationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using ElectricTransportBlog.Core.Constants;
using ElectricTransportBlog.Core.Contracts;
using ElectricTransportBlog.Core.Extensions;
using ElectricTransportBlog.Core.Models.Publication;
using ElectricTransportBlog.Core.Models.PublicationComments;

namespace ElectricTransportBlog.Controllers
{
    public class PublicationController : Controller
    {
        private readonly IPublicationService publication;
        private readonly IUserService users;
        private readonly IPublicationCommentsService comments;

        public PublicationController(IPublicationService news, IUserService users, IPublicationCommentsService comments)
        {
            this.publication = news;
            this.users = users;
            this.comments = comments;
        }

        public IActionResult All(int p = 1, int s = 10)
        {
            var latestPublication = this.publication.All(p, s);

            return View(latestPublication);
        }

        public IActionResult Details(Guid id)
        {
            if (id == Guid.Empty)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var publication = this.publication.Details(id);

            if (publication == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction("All");
            }

            return View(publication);
        }

        [Authorize(Roles = $"{UserConstants.Administrator},{UserConstants.Moderator}")]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = $"{UserConstants.Administrator},{UserConstants.Moderator}")]
        public async Task<IActionResult> AddAsync(PublicationAddFormModel publication)
        {
            var userId = this.users.IdByUser(this.User.Id());

            if (userId == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            byte[] fileArray = null;

            using (var memoryStream = new MemoryStream())
            {
                await publication.FileUpload.PhotoFile.CopyToAsync(memoryStream);

                string fileExt = Path.GetExtension(publication.FileUpload.PhotoFile.FileName.ToLower());

                if (fileExt == ".jpeg" || fileExt == ".jpg")
                {
                    // Upload the file if less than 2 MB
                    if (memoryStream.Length < 2097152)
                    {
                        fileArray = memoryStream.ToArray();
                    }
                    else
                    {
                        TempData[MessageConstants.ErrorMessage] = "Размерът на снимката е твърде голям! Моля качете снимка до 2MB!";
                        return Redirect(Request.Path);
                    }
                }
                else
                {
                    TempData[MessageConstants.ErrorMessage] = "Само .jpeg/.jpg файлове са разрешени!";
                    return Redirect(Request.Path);
                }
            }

            var publicationId = this.publication.CreatePublication(
                publication.Title,
                publication.Description,
                DateTime.Now,
                userId,
                fileArray,
                false);

            TempData[MessageConstants.SuccessMessage] = "Новината беше успешно добавена.";
            return RedirectToAction("All");
        }

        [Authorize(Roles = $"{UserConstants.Administrator},{UserConstants.Moderator}")]
        public IActionResult Edit(Guid id)
        {
            var userId = this.users.IdByUser(this.User.Id());

            if (userId == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var news = this.publication.Details(id);

            var newsForm = this.publication.EditViewData(news.Id);

            return View(newsForm);
        }

        [HttpPost]
        [Authorize(Roles = $"{UserConstants.Administrator},{UserConstants.Moderator}")]
        public async Task<IActionResult> EditAsync(Guid id, PublicationEditFormModel publication)
        {
            byte[] fileArray = null;

            if (publication.FileUpload != null)
            {

                using (var memoryStream = new MemoryStream())
                {
                    await publication.FileUpload.PhotoFile.CopyToAsync(memoryStream);

                    string fileExt = Path.GetExtension(publication.FileUpload.PhotoFile.FileName.ToLower());

                    if (fileExt == ".jpeg" || fileExt == ".jpg")
                    {
                        // Upload the file if less than 2 MB
                        if (memoryStream.Length < 2097152)
                        {
                            fileArray = memoryStream.ToArray();
                        }
                        else
                        {
                            TempData[MessageConstants.ErrorMessage] = "Размерът на снимката е твърде голям! Моля качете снимка до 2MB!";
                            return Redirect(Request.Path);
                        }
                    }
                    else
                    {
                        TempData[MessageConstants.ErrorMessage] = "Само .jpeg/.jpg файлове са разрешени!";
                        return Redirect(Request.Path);
                    }
                }
            }

            var edited = this.publication.Edit(
                id,
                publication.Title,
                publication.Description,
                fileArray);

            if (!edited)
            {
                return BadRequest();
            }

            TempData[MessageConstants.SuccessMessage] = "Новината беше успешно редактирана.";
            return Redirect($"../../Publication/Details/{id}");
        }

        [Authorize(Roles = $"{UserConstants.Administrator},{UserConstants.Moderator}")]
        public IActionResult Delete(Guid id)
        {
            var userId = this.users.IdByUser(this.User.Id());

            if (userId == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var news = this.publication.Details(id);

            var newsForm = this.publication.DeleteViewData(news.Id);

            return View(newsForm);
        }

        [HttpPost]
        [Authorize(Roles = $"{UserConstants.Administrator},{UserConstants.Moderator}")]
        public IActionResult Delete(Guid id, PublicationDeleteModel news)
        {

            var deleted = this.publication.Delete(id, true);

            if (!deleted)
            {
                return BadRequest();
            }

            TempData[MessageConstants.SuccessMessage] = "Новината беше успешно изтрита.";
            return RedirectToAction("All");
        }

        [HttpPost]
        [Authorize]
        public IActionResult Details(Guid id, CommentAddFormModel comment)
        {
            var userId = this.users.IdByUser(this.User.Id());

            if (userId == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var edited = this.comments.CreatePublicationComment(
                comment.Content,
                DateTime.Now,
                userId,
                id);

            TempData[MessageConstants.SuccessMessage] = "Успешно публикувахте коментар.";
            return Redirect(Request.Path);
        }
    }
}

ElectricTransportBlog/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ElectricTransportBlog.Core.Constants;
using ElectricTransportBlog.Core.Contracts;
using ElectricTransportBlog.Core.Extensions;

namespace ElectricTransportBlog.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService users;

        public UserController(IUserService users)
        {
            this.users = users;
        }

        [Authorize]
        public IActionResult MyProfile()
        {
            return View();
        }

        public IActionResult UserProfile(string id)
        {

            var detailsForm = this.users.UserDetails(id);

            return View(detailsForm);
        }
    }
}

ElectricTransportBlog/Views/Publication/Add.cshtml
@using ElectricTransportBlog.Core.Models.Publication
@model PublicationAddFormModel

@{
    ViewData["Title"] = "Добави публикация";
}

<div class="row">
    <div class="col-md-10 offset-md-1">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Добави публикация</h3>
            </div>
            <form enctype="multipart/form-data" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="Title"></label>
                        <input asp-for="Title" class="form-control" placeholder="Добавете заглавие">
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description"></label>
                        <textarea asp-for="Description" id="richtextarea" class="form-control" rows="8" placeholder="Добавете съдържанието тук"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-4">
                        <label asp-for="FileUpload.PhotoFile" class="control-label"></label>
                        <input asp-for="FileUpload.PhotoFile" type="file" class="form-control">
                        <span asp-validation-for="FileUpload.PhotoFile" class="text-danger"></span>
                    </div>
                </div>
                <div class="card-body">
                    <a asp-controller="Publication" asp-action="All" class="btn btn-secondary">Отказ</a>
                    <input asp-page-handler="Upload" class="btn btn-primary float-right" type="submit" value="Публикувай">
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ElectricTransportBlog/Views/Publication/All.cshtml
@using ElectricTransportBlog.Core.Models.Publication
@model PublicationPaginationModel

@{
    ViewBag.Title = "Публикации";
}

@if (!Model.Publications.Any())
{
    <h2 class="text-center">В сайта все още няма публикации!</h2>
}
else
{
    <div class="row">
        @foreach (var publication in Model.Publications)
        {
            <div class="col-md-10 offset-md-1">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="product-title"><a asp-controller="Publication" asp-action="Details" asp-route-id="@publication.Id">@publication.Title</a></h3>
                    </div>
                    <div class="card-body">
                        <article>
                            <header class="entry-header">
                                <meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
                                <div class="entry-thumbnail">
                                    <img class="img-fluid" src="@publication.ImgUrlFormDatabase" alt="Снимка">
                                </div>
                                <b class="entry-date right">Публикувана на: @publication.Date.ToString("D")</b>
                                <b class="comments-count float-right">Брой коментари: @publication.CommentsCount</b>
                            </header>
                            <div class="entry-content">
                                <p class="short-content">
                                    @publication.Description
                                </p>
                                <a asp-controller="Publication" asp-action="Details" asp-route-id="@publication.Id" class="btn btn-primary float-right">Прочети още</a>
                            </div>
                        </article>
                    </div>
                </div>
            </div>
        }
    </div>
    <paging page-no="Model.PageNo"
        page-size="Model.PageSize"
        total-records="Model.TotalRecords"
        page-size-dropdown-items="2-5-10">
    </paging>
}

ElectricTransportBlog/Views/Publication/Delete.cshtml
@using ElectricTransportBlog.Core.Models.Publication
@model PublicationDeleteModel

@{
    ViewData["Title"] = "Изтриване на публикация";
}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="card card-danger">
            <div class="card-header">
                <h3 class="card-title">Сигурен ли сте, че искате да изтриете публикация със заглавие:</h3>
            </div>
            <form method="post">
                <div class="card-body">
                    <div class="form-group text-center">
                        <h3 class="text-center" asp-for="Title">@Model.Title</h3><br>
                        <b class="text-center" asp-for="Date">От дата: @Model.Date.ToString("D")</b><br>
                        <img class="img-fluid" src="@Model.ImgUrlFormDatabase" alt="Снимка">
                    </div>
                </div>
                <div class="card-body">
                    <a asp-controller="Publication" asp-action="All" class="btn btn-secondary">Отказ</a>
                    <button type="submit" class="btn btn-danger float-right">Изтрий</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ElectricTransportBlog/Views/Publication/Details.cshtml
@using Microsoft.AspNetCore.Identity
@using ElectricTransportBlog.Core.Constants
@using ElectricTransportBlog.Core.Models.Publication
@using ElectricTransportBlog.Core.Models.PublicationComments
@using ElectricTransportBlog.Infrastructure.Data.Models

@model PublicationCommentsModel
@inject SignInManager<WebsiteUser> SignInManager
@inject UserManager<WebsiteUser> UserManager

@{
    ViewBag.Title = @Model.Title;
}

<div class="row">
    <div class="col-md-10 offset-md-1">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="product-title"><a asp-controller="Publication" asp-action="Details" asp-route-id="@Model.Id">@Model.Title</a></h3>
            </div>
            <div class="card-body">
                <article>
                    <header class="entry-header">
                        <meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
                        <div class="entry-thumbnail">
                            <img class="img-fluid" src="@Model.ImgUrlFormDatabase" alt="Снимка">
                        </div>
                        <b class="entry-date right">Публикувана на: @Model.Date.ToString("D")</b>
                    </header>
                    <div class="entry-content">
                        <p class="short-content">
                            @Html.Raw(@Model.Description)
                        </p>
                        <h4> Автор: <a asp-controller="User" asp-action="UserProfile" asp-route-id="@UserManager.Users.Where(x => x.UserName == Model.Author.UserName).Select(x => x.Id).First()" >@Model.Author.UserName</a></h4>
                    </div>
                    @if (this.User.IsInRole(UserConstants.Administrator) || this.User.IsInRole(UserConstants.Moderator))
                    {
                        <a asp-controller="Publication" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger float-right">Изтрий</a>
                        <a asp-controller="Publication" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning float-left">Редактирай</a>
                    }
                </article>
            </div>
        </div>
    </div>
    <div class="col-md-12 text-center">
    </div>
    <div class="col-md-10 offset-md-1">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fa fa-comments"></i>
                    Всички Коментари <b>@Model.PublicationComments.Count</b>
                </h3>
            </div>
            @if (Model.PublicationComments.Count == 0)
            {
                <h2 class="text-center">Няма коментари!</h2>
            }
            else
            {
                @foreach (var comment in Model.PublicationComments)
                {
                    <div>
                        <blockquote>
                            <small>Автор: <cite title="Source Title"><a asp-controller="User" asp-action="UserProfile" asp-route-id="@UserManager.Users.Where(x => x.UserName == comment.User.UserName).Select(x => x.Id).First()" >@comment.User.UserName</a></cite></small>
                            <p>@comment.Content</p>
                            <small>Публикуван на: <cite title="Source Title">@comment.Date.ToString("f")</cite></small>
                            @if (this.User.IsInRole(UserConstants.Administrator) || this.UserManager.GetUserId(User) == comment.User.Id || this.User.IsInRole(UserConstants.Moderator))
                            {
                                <a asp-controller="PublicationComments" asp-action="Delete" asp-route-id="@comment.Id" class="btn btn-danger float-right">Изтрий</a>
                                <a asp-controller="PublicationComments" asp-action="Edit" asp-route-id="@comment.Id" class="btn btn-warning float-right">Редактирай</a>
                            }
                            @if (comment.LastEditedOn != null)
                            {
                                <br>

                                <small>Последна редакция на: <cite title="Source Title">@comment.LastEditedOn.Value.ToString("f")</cite></small>
                            }
                        </blockquote>
                    </div>
                }
            }
        </div>
    </div>
    @if (this.SignInManager.IsSignedIn(User))
    {
        <partial name="_PartialAddComment" />
    }
    else
    {
        <div class="col-md-10 offset-md-1">
            <h3 class="text-center">За да коментирате, <a asp-area="Identity" asp-page="/Account/Login">влезте</a> в профила си или се <a asp-area="Identity" asp-page="/Account/Register">регистрирайте</a>.</h3>
        </div>
    }
</div>

@section Scripts {
<partial name="_ValidationScriptsPartial" />
}

ElectricTransportBlog/Views/Publication/Edit.cshtml
@using ElectricTransportBlog.Core.Models.Publication
@model PublicationEditFormModel

@{
    ViewData["Title"] = "Редактирай публикация";
}

<div class="row">
    <div class="col-md-10 offset-md-1">
        <div class="card card-warning">
            <div class="card-header">
                <h3 class="card-title">Редактирай публикация</h3>
            </div>
            <form enctype="multipart/form-data" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="Title"></label>
                        <input asp-for="Title" class="form-control" placeholder="Добавете заглавие">
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description"></label>
                        <textarea asp-for="Description" id="richtextarea" class="form-control" rows="15" placeholder="Добавете съдържанието тук"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-4">
                        <label asp-for="FileUpload.PhotoFile" class="control-label"></label>
                        <input asp-for="FileUpload.PhotoFile" type="file" class="form-control">
                        <span asp-validation-for="FileUpload.PhotoFile" class="text-danger"></span>
                    </div>
                </div>
                <div class="card-body">
                    <a asp-controller="Publication" asp-action="All" class="btn btn-secondary">Отказ</a>
                    <input asp-page-handler="Upload" class="btn btn-warning float-right" type="submit" value="Редактирай">
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ElectricTransportBlog/Views/Publication/_PartialAddComment.cshtml
@using ElectricTransportBlog.Core.Models.Publication
@model PublicationCommentsModel

<div class="col-md-10 offset-md-1">
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Добави коментар</h3>
        </div>
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="card-body">
                <div class="form-group">
                    <label asp-for="Content"></label>
                    <textarea asp-for="Content" class="form-control" rows="4" placeholder="Напишете коментара си тук"></textarea>
                    <span asp-validation-for="Content" class="text-danger"></span>
                </div>
                <div>
                    <button type="submit" class="btn btn-primary float-right">Напиши</button>
                </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}