ElectricTransportBlog/Controllers/LineController.cs
using ElectricTransportBlog.Core.Constants;
using ElectricTransportBlog.Core.Contracts;
using ElectricTransportBlog.Core.Extensions;
using ElectricTransportBlog.Core.Models.Line;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ElectricTransportBlog.Controllers
{
    public class LineController : Controller
    {
        private readonly ILineService lines;
        private readonly IUserService users;

        public LineController(ILineService lines, IUserService users)
        {
            this.lines = lines;
            this.users = users;
        }

        [Authorize(Roles = UserConstants.Administrator)]
        public IActionResult Add()
        {
            return View(new LineAddFormModel
            {
                LineTypes = this.lines.AllLineTypes()
            });
        }

        [HttpPost]
        [Authorize(Roles = UserConstants.Administrator)]
        public async Task<IActionResult> AddAsync(Guid id, LineAddFormModel line)
        {
            var userId = this.users.IdByUser(this.User.Id());

            if (userId == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var lineId = this.lines.CreateLine(
                line.Number,
                line.ShortLineDescription,
                line.LineDescription,
                line.WorkDayInterval,
                line.WeekendInterval,
                line.LineTypeId,
                id
                );

            TempData[MessageConstants.SuccessMessage] = "Успешно добавихте линията.";
            return Redirect($"../../TransportNetwork/Details/{id}");
        }

        public IActionResult Details(Guid id)
        {
            if (id == Guid.Empty)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var line = this.lines.Details(id);

            if (line == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction("All");
            }

            return View(line);
        }

        [Authorize(Roles = UserConstants.Administrator)]
        public IActionResult Edit(Guid id)
        {
            var userId = this.users.IdByUser(this.User.Id());

            if (userId == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var lineForm = this.lines.EditViewData(id);

            lineForm.LineTypes = this.lines.AllLineTypes();

            return View(lineForm);
        }

        [HttpPost]
        [Authorize(Roles = UserConstants.Administrator)]
        public IActionResult Edit(Guid id, LineEditFormModel line)
        {
            var edited = this.lines.Edit(
                id,
                line.Number,
                line.ShortLineDescription,
                line.LineDescription,
                line.WorkDayInterval,
                line.WeekendInterval,
                line.LineTypeId
                );

            if (!edited)
            {
                return BadRequest();
            }

            TempData[MessageConstants.SuccessMessage] = "Информацията за линията беше успешно редактирана.";
            return Redirect($"../../TransportNetwork/All");
        }

        [Authorize(Roles = UserConstants.Administrator)]
        public IActionResult Delete(Guid id)
        {
            var userId = this.users.IdByUser(this.User.Id());

            if (userId == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var lineForm = this.lines.DeleteViewData(id);

            return View(lineForm);
        }

        [HttpPost]
        [Authorize(Roles = UserConstants.Administrator)]
        public IActionResult Delete(Guid id, LineDeleteModel line)
        {

            var deleted = this.lines.Delete(id);

            if (!deleted)
            {
                return BadRequest();
            }

            TempData[MessageConstants.SuccessMessage] = "Линията беше успешно изтрита.";
            return Redirect($"../../TransportNetwork/All");
        }
    }
}

ElectricTransportBlog/Controllers/TransportNetworkController.cs
using ElectricTransportBlog.Core.Constants;
using ElectricTransportBlog.Core.Contracts;
using ElectricTransportBlog.Core.Extensions;
using ElectricTransportBlog.Core.Models.TransportNetwork;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ElectricTransportBlog.Controllers
{
    public class TransportNetworkController : Controller
    {
        private readonly ITransportNetworkService transportNetwork;
        private readonly IUserService users;

        public TransportNetworkController(ITransportNetworkService transportNetwork, IUserService users)
        {
            this.transportNetwork = transportNetwork;
            this.users = users;
        }

        public IActionResult All(int p = 1, int s = 10)
        {
            var latestPublication = this.transportNetwork.All(p, s);

            return View(latestPublication);
        }

        [Authorize(Roles = $"{UserConstants.Administrator},{UserConstants.Moderator}")]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = $"{UserConstants.Administrator}")]
        public async Task<IActionResult> AddAsync(TransportNetworkAddFormModel transportNetwork)
        {
            var userId = this.users.IdByUser(this.User.Id());

            if (userId == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            byte[] fileArray = null;

            using (var memoryStream = new MemoryStream())
            {
                await transportNetwork.FileUpload.PhotoFile.CopyToAsync(memoryStream);

                string fileExt = Path.GetExtension(transportNetwork.FileUpload.PhotoFile.FileName.ToLower());

                if (fileExt == ".jpeg" || fileExt == ".jpg")
                {
                    // Upload the file if less than 2 MB
                    if (memoryStream.Length < 2097152)
                    {
                        fileArray = memoryStream.ToArray();
                    }
                    else
                    {
                        TempData[MessageConstants.ErrorMessage] = "Размерът на снимката е твърде голям! Моля качете снимка до 2MB!";
                        return Redirect(Request.Path);
                    }
                }
                else
                {
                    TempData[MessageConstants.ErrorMessage] = "Само .jpeg/.jpg файлове са разрешени!";
                    return Redirect(Request.Path);
                }
            }

            var transportNetworkId = this.transportNetwork.Create(
                transportNetwork.Town,
                transportNetwork.Description,
                userId,
                fileArray,
                false);

            TempData[MessageConstants.SuccessMessage] = "Мрежата беше успешно добавена.";
            return RedirectToAction("All");
        }

        [Authorize(Roles = $"{UserConstants.Administrator}")]
        public IActionResult Edit(Guid id)
        {
            var userId = this.users.IdByUser(this.User.Id());

            if (userId == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var transportNetwork = this.transportNetwork.Details(id);

            var transportNetworkForm = this.transportNetwork.EditViewData(transportNetwork.Id);

            return View(transportNetworkForm);
        }

        [HttpPost]
        [Authorize(Roles = $"{UserConstants.Administrator}")]
        public async Task<IActionResult> EditAsync(Guid id, TransportNetworkEditFormModel transportNetwork)
        {
            byte[] fileArray = null;

            if (transportNetwork.FileUpload != null)
            {

                using (var memoryStream = new MemoryStream())
                {
                    await transportNetwork.FileUpload.PhotoFile.CopyToAsync(memoryStream);

                    string fileExt = Path.GetExtension(transportNetwork.FileUpload.PhotoFile.FileName.ToLower());

                    if (fileExt == ".jpeg" || fileExt == ".jpg")
                    {
                        // Upload the file if less than 2 MB
                        if (memoryStream.Length < 2097152)
                        {
                            fileArray = memoryStream.ToArray();
                        }
                        else
                        {
                            TempData[MessageConstants.ErrorMessage] = "Размерът на снимката е твърде голям! Моля качете снимка до 2MB!";
                            return Redirect(Request.Path);
                        }
                    }
                    else
                    {
                        TempData[MessageConstants.ErrorMessage] = "Само .jpeg/.jpg файлове са разрешени!";
                        return Redirect(Request.Path);
                    }
                }
            }

            var edited = this.transportNetwork.Edit(
                id,
                transportNetwork.Town,
                transportNetwork.Description,
                fileArray);

            if (!edited)
            {
                return BadRequest();
            }

            TempData[MessageConstants.SuccessMessage] = "Мрежата беше успешно редактирана.";
            return Redirect($"../../TransportNetwork/Details/{id}");
        }

        [Authorize(Roles = $"{UserConstants.Administrator}")]
        public IActionResult Delete(Guid id)
        {
            var userId = this.users.IdByUser(this.User.Id());

            if (userId == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var transportNetwork = this.transportNetwork.Details(id);

            var transportNetworkForm = this.transportNetwork.DeleteViewData(transportNetwork.Id);

            return View(transportNetworkForm);
        }

        [HttpPost]
        [Authorize(Roles = $"{UserConstants.Administrator}")]
        public IActionResult Delete(Guid id, TransportNetworkDeleteModel transportNetwork)
        {

            var deleted = this.transportNetwork.Delete(id, true);

            if (!deleted)
            {
                return BadRequest();
            }

            TempData[MessageConstants.SuccessMessage] = "Мрежата беше успешно изтрита.";
            return RedirectToAction("All");
        }

        public IActionResult Details(Guid id)
        {
            if (id == Guid.Empty)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var transportNetwork = this.transportNetwork.Details(id);

            if (transportNetwork == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction("All");
            }

            return View(transportNetwork);
        }

        public IActionResult AddContact(Guid id)
        {
            var userId = this.users.IdByUser(this.User.Id());

            if (userId == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var transportNetwork = this.transportNetwork.Details(id);

            var transportNetworkForm = this.transportNetwork.EditContactViewData(transportNetwork.Id);

            return View(transportNetworkForm);
        }

        [HttpPost]
        [Authorize(Roles = $"{UserConstants.Administrator}")]
        public async Task<IActionResult> AddContactAsync(Guid id, TransportNetworkContactEditModel transportNetwork)
        {
            var edited = this.transportNetwork.EditContact(
                id,
                transportNetwork.Email,
                transportNetwork.PhoneNumber,
                transportNetwork.WebPage);

            if (!edited)
            {
                return BadRequest();
            }

            TempData[MessageConstants.SuccessMessage] = "Контактът беше успешно редактиран.";
            return Redirect($"../../TransportNetwork/Details/{id}");
        }
    }
}

ElectricTransportBlog/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ElectricTransportBlog.Core.Constants;
using ElectricTransportBlog.Core.Contracts;
using ElectricTransportBlog.Core.Extensions;

namespace ElectricTransportBlog.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService users;

        public UserController(IUserService users)
        {
            this.users = users;
        }

        [Authorize]
        public IActionResult MyProfile()
        {
            return View();
        }

        public IActionResult UserProfile(string id)
        {

            var detailsForm = this.users.UserDetails(id);

            return View(detailsForm);
        }
    }
}

ElectricTransportBlog/Views/TransportNetwork/Add.cshtml
@using ElectricTransportBlog.Core.Models.TransportNetwork
@model TransportNetworkAddFormModel

@{
    ViewData["Title"] = "Добави транспортна мрежа";
}

<div class="row">
    <div class="col-md-10 offset-md-1">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Добави транспортна мрежа</h3>
            </div>
            <form enctype="multipart/form-data" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="Town"></label>
                        <input asp-for="Town" class="form-control" placeholder="Име на града чиято система искате да добавите">
                        <span asp-validation-for="Town" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description"></label>
                        <textarea asp-for="Description" class="form-control" rows="8" placeholder="Добавете описание тук"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FileUpload.PhotoFile" class="control-label"></label>
                        <input asp-for="FileUpload.PhotoFile" type="file" class="form-control">
                        <span asp-validation-for="FileUpload.PhotoFile" class="text-danger"></span>
                    </div>
                </div>
                <div class="card-body">
                    <a asp-controller="TransportNetwork" asp-action="All" class="btn btn-secondary">Отказ</a>
                    <input asp-page-handler="Upload" class="btn btn-primary float-right" type="submit" value="Публикувай">
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ElectricTransportBlog/Views/TransportNetwork/AddContact.cshtml
@using ElectricTransportBlog.Core.Models.TransportNetwork
@model TransportNetworkContactEditModel

@{
    ViewData["Title"] = "Добави/Промени Контакт";
}

<div class="row">
    <div class="col-md-10 offset-md-1">
        <div class="card card-warning">
            <div class="card-header">
                <h3 class="card-title">Добави/Промени Контакт</h3>
            </div>
            <form enctype="multipart/form-data" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="Email"></label>
                        <input asp-for="Email" class="form-control" placeholder="Добавете имейл">
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PhoneNumber"></label>
                        <input asp-for="PhoneNumber" class="form-control" placeholder="Добавете телефонен номер">
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="WebPage"></label>
                        <input asp-for="WebPage" class="form-control" placeholder="Адрес на уеб страница тук">
                        <span asp-validation-for="WebPage" class="text-danger"></span>
                    </div>
                </div>
                <div class="card-body">
                    <a asp-controller="TransportNetwork" asp-action="All" class="btn btn-secondary">Отказ</a>
                    <input asp-page-handler="Upload" class="btn btn-warning float-right" type="submit" value="Запази промените">
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ElectricTransportBlog/Views/TransportNetwork/All.cshtml
@using ElectricTransportBlog.Core.Models.TransportNetwork
@model TransportNetworkPaginationModel

@{
    ViewBag.Title = "Транспортни Мрежи";
}

@if (!Model.TransportNetworks.Any())
{
    <h2 class="text-center">В сайта все още няма добавени транспортни мрежи!</h2>
}
else
{
    <div class="row">
        @foreach (var transportNetwork in Model.TransportNetworks)
        {
            <div class="col-md-6">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="product-title"><a asp-controller="TransportNetwork" asp-action="Details" asp-route-id="@transportNetwork.Id">@transportNetwork.Town</a></h3>
                    </div>
                    <div class="card-body">
                        <article>
                            <header class="entry-header">
                                <meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
                                <div class="entry-thumbnail">
                                    <img class="img-fluid" style="height:400px; width:100%; object-fit:contain;" src="@transportNetwork.ImgUrlFormDatabase" alt="Снимка">
                                </div>
                                <b class="comments-count float-right">Брой линии: @transportNetwork.LinesCount</b>
                            </header>
                            <div class="entry-content">
                                <p class="short-content">
                                    @transportNetwork.Description
                                </p>
                                <a asp-controller="TransportNetwork" asp-action="Details" asp-route-id="@transportNetwork.Id" class="btn btn-primary float-right">Прочети още</a>
                            </div>
                        </article>
                    </div>
                </div>
            </div>
        }
    </div>
    <paging page-no="Model.PageNo"
        page-size="Model.PageSize"
        total-records="Model.TotalRecords"
        page-size-dropdown-items="2-5-10">
    </paging>
}

ElectricTransportBlog/Views/TransportNetwork/Delete.cshtml
@using ElectricTransportBlog.Core.Models.TransportNetwork
@model TransportNetworkDeleteModel

@{
    ViewData["Title"] = "Изтриване на мрежа";
}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="card card-danger">
            <div class="card-header">
                <h3 class="card-title">Сигурен ли сте, че искате да изтриете мрежата на град:</h3>
            </div>
            <form method="post">
                <div class="card-body">
                    <div class="form-group text-center">
                        <h3 class="text-center" asp-for="Title">@Model.Town</h3><br>
                        <img class="img-fluid" src="@Model.ImgUrlFormDatabase" alt="Снимка">
                    </div>
                </div>
                <div class="card-body">
                    <a asp-controller="TransportNetwork" asp-action="All" class="btn btn-secondary">Отказ</a>
                    <button type="submit" class="btn btn-danger float-right">Изтрий</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ElectricTransportBlog/Views/TransportNetwork/Details.cshtml
@using ElectricTransportBlog.Core.Models.TransportNetwork
@using Microsoft.AspNetCore.Identity
@using ElectricTransportBlog.Core.Constants
@using ElectricTransportBlog.Infrastructure.Data.Models

@model TransportNetworkContactLinesModel
@inject SignInManager<WebsiteUser> SignInManager
@inject UserManager<WebsiteUser> UserManager

@{
    ViewBag.Title = @Model.Town;
}

<div class="row">
    <div class="col-md-12">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="product-title"><a asp-controller="TransportNetwork" asp-action="Details" asp-route-id="@Model.Id">@Model.Town</a></h3>
            </div>
            <div class="card-body">
                <article>
                    <header class="entry-header">
                        <meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
                        <div class="entry-thumbnail">
                            <img class="img-fluid" src="@Model.ImgUrlFormDatabase" alt="Снимка">
                        </div>
                        @*<b class="entry-date right">Публикувана на: @Model.Date.ToString("D")</b>*@
                    </header>
                    <div class="entry-content">
                        <h4> Публикувано от: <a asp-controller="User" asp-action="UserProfile" asp-route-id="@UserManager.Users.Where(x => x.UserName == Model.PublishedBy.UserName).Select(x => x.Id).First()" >@Model.PublishedBy.UserName</a></h4>
                    </div>
                    <div class="card-body">
                        <dl class="row">
                            <dt class="col-sm-3">Описание:</dt>
                            <dd class="col-sm-9">@Model.Description</dd>
                            <dt class="col-sm-12 text-center">Контакти</dt>
                            @if (Model.Contact != null)
                            {
                                <dt class="col-sm-3">Имейл:</dt>
                                <dd class="col-sm-9">@(Model.Contact.Email != null ? Model.Contact.Email : "Няма информация")</dd>
                                <dt class="col-sm-3">Телефон:</dt>
                                <dd class="col-sm-9">@(Model.Contact.PhoneNumber != null ? Model.Contact.PhoneNumber : "Няма информация")</dd>
                                <dt class="col-sm-3">Уебсайт:</dt>
                                <dd class="col-sm-9">
                                    <div>
                                        <a href="@(Model.Contact.WebPage != null ? @Model.Contact.WebPage : $"../../TransportNetwork/Details/{Model.Id}")">@(Model.Contact.WebPage != null ? @Model.Contact.WebPage : "Няма информация")</a>
                                    </div>
                                </dd>
                            }
                            else
                            {
                                <p>Няма добавен контакт!</p>
                            }
                            <dt class="col-sm-12 text-center">Линии</dt>
                            @if (Model.Lines.Count() != 0)
                            {
                                <div class="col-12">
                                    <table id="example" class="table table-bordered table-hover dataTable dtr-inline">
                                        <thead>
                                            <tr class="table-success">
                                                <th tabindex="0" rowspan="1" colspan="1" width="30%">Номер</th>
                                                <th tabindex="0" rowspan="5" colspan="1" width="70%">Кратко описание</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var line in Model.Lines)
                                            {
                                                <tr class="@line.LineType.ClassColor">
                                                    <td><a asp-controller="Line" asp-action="Details" asp-route-id="@line.Id">@line.Number</a></td>
                                                    <td>@line.ShortLineDescription</td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            }
                            else
                            {
                                <div class="col-12">
                                    <h3 class="text-center">Няма добавени линии!</h3>
                                </div>
                            }
                        </dl>
                    </div>
                    @if (this.User.IsInRole(UserConstants.Administrator))
                    {
                        <div class="d-flex justify-content-center justify-content-between">
                            <a asp-controller="TransportNetwork" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning float-left">Редактирай</a>
                            <a asp-controller="TransportNetwork" asp-action="AddContact" asp-route-id="@Model.Id" class="btn btn-primary">Добави/Промени Контакт</a>
                            <a asp-controller="Line" asp-action="Add" asp-route-id="@Model.Id" class="btn btn-success">Добави линия</a>
                            <a asp-controller="TransportNetwork" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger float-right">Изтрий</a>
                        </div>
                    }
                </article>
            </div>
        </div>
    </div>
    <div class="col-md-12 text-center">
    </div>

    <div class="col-12">
    <h2 class="text-center">Брой електрически линии: @Model.Lines.Count()</h2>
        <table class="table text-center col-md-6 offset-md-3">
            <thead>
              <tr>
                <th scope="col">Цветово кодиране</th>
              </tr>
            </thead>
            <tbody>
                <tr class="table-danger">
                  <th scope="row">Трамвайна линия</th>
                </tr>
                <tr class="table-primary">
                  <th scope="row">Тролейбусна линия</th>
                </tr>
                <tr class="table-warning">
                  <th scope="row">Електробусна линия</th>
                </tr>
            </tbody>
        </table>
    </div>

@section Scripts {
<partial name="_ValidationScriptsPartial" />
}

ElectricTransportBlog/Views/TransportNetwork/Edit.cshtml
@using ElectricTransportBlog.Core.Models.TransportNetwork
@model TransportNetworkEditFormModel

@{
    ViewData["Title"] = "Редактирай транспортна мрежа";
}

<div class="row">
    <div class="col-md-10 offset-md-1">
        <div class="card card-warning">
            <div class="card-header">
                <h3 class="card-title">Редактирай транспортната мрежа</h3>
            </div>
            <form enctype="multipart/form-data" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="Town"></label>
                        <input asp-for="Town" class="form-control" placeholder="Добавете заглавие">
                        <span asp-validation-for="Town" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description"></label>
                        <textarea asp-for="Description" class="form-control" rows="8" placeholder="Добавете съдържанието тук"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-4">
                        <label asp-for="FileUpload.PhotoFile" class="control-label"></label>
                        <input asp-for="FileUpload.PhotoFile" type="file" class="form-control">
                        <span asp-validation-for="FileUpload.PhotoFile" class="text-danger"></span>
                    </div>
                </div>
                <div class="card-body">
                    <a asp-controller="TransportNetwork" asp-action="All" class="btn btn-secondary">Отказ</a>
                    <input asp-page-handler="Upload" class="btn btn-warning float-right" type="submit" value="Редактирай">
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}