ElectricTransportBlog/Areas/RoleManage/Controllers/UserRoleController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ElectricTransportBlog.Core.Constants;
using ElectricTransportBlog.Core.Contracts;
using ElectricTransportBlog.Core.Models.Users;
using ElectricTransportBlog.Infrastructure.Data.Models;

namespace ElectricTransportBlog.Areas.RoleManage.Controllers
{
    [Area("RoleManage")]
    public class UserRoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;

        private readonly UserManager<WebsiteUser> userManager;

        private readonly IUserRoleService service;

        public UserRoleController(
            RoleManager<IdentityRole> roleManager,
            UserManager<WebsiteUser> userManager,
            IUserRoleService service)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
            this.service = service;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> ManageUsers()
        {
            var users = await service.GetUsers();

            return View(users);
        }

        public async Task<IActionResult> Roles(string id)
        {
            var user = await service.GetUserById(id);
            var model = new UserRolesModel()
            {
                UserId = user.Id,
                Username = user.UserName,
            };


            ViewBag.RoleItems = roleManager.Roles
                .ToList()
                .Select(r => new SelectListItem()
                {
                    Text = r.Name,
                    Value = r.Name,
                    Selected = userManager.IsInRoleAsync(user, r.Name).Result
                }).ToList();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Roles(UserRolesModel model)
        {
            var user = await service.GetUserById(model.UserId);
            var userRoles = await userManager.GetRolesAsync(user);
            await userManager.RemoveFromRolesAsync(user, userRoles);

            if (model.RoleNames?.Length > 0)
            {
                await userManager.AddToRolesAsync(user, model.RoleNames);
            }

            return RedirectToAction(nameof(ManageUsers));
        }

        public async Task<IActionResult> Edit(string id)
        {
            var model = await service.GetUserForEdit(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserEditModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (await service.UpdateUser(model))
            {
                ViewData[MessageConstants.SuccessMessage] = "Успешено записано!";
            }
            else
            {
                ViewData[MessageConstants.ErrorMessage] = "Възникна грешка!";
            }

            return View(model);
        }

        //public async Task<IActionResult> CreateRole()
        //{
        //    await roleManager.CreateAsync(new IdentityRole()
        //    {
        //        Name = "Модератор"
        //    });

        //    return Ok();
        //}
    }
}

ElectricTransportBlog/Controllers/DownloadController.cs
using ElectricTransportBlog.Core.Constants;
using ElectricTransportBlog.Core.Contracts;
using ElectricTransportBlog.Core.Extensions;
using ElectricTransportBlog.Core.Models.Download;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ElectricTransportBlog.Controllers
{
    public class DownloadController : Controller
    {
        private readonly IDownloadService downloads;
        private readonly IUserService users;

        public DownloadController(IDownloadService downloads, IUserService users)
        {
            this.downloads = downloads;
            this.users = users;
        }

        public IActionResult All()
        {
            var downloads = this.downloads.All();

            return View(downloads);
        }

        [Authorize]
        [Authorize(Roles = UserConstants.Administrator)]
        public IActionResult AddPDF()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = UserConstants.Administrator)]
        public async Task<IActionResult> AddPDFAsync(Guid id, DownloadAddFormModel download)
        {
            var userId = this.users.IdByUser(this.User.Id());

            if (userId == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            byte[] fileArray = null;

            using (var memoryStream = new MemoryStream())
            {
                await download.FileUpload.FilePDF.CopyToAsync(memoryStream);

                string fileExt = Path.GetExtension(download.FileUpload.FilePDF.FileName.ToLower());

                if (fileExt == ".pdf" || fileExt == ".PDF")
                {
                    // Upload the file if less than 2 MB
                    if (memoryStream.Length < 2097152)
                    {
                        fileArray = memoryStream.ToArray();
                    }
                    else
                    {
                        TempData[MessageConstants.ErrorMessage] = "Размерът на PDF файлът е твърде голям! Ограничението за размер е до 2MB!";
                        return Redirect(Request.Path);
                    }
                }
                else
                {
                    TempData[MessageConstants.ErrorMessage] = "Само .PDF/.pdf файлове са разрешени!";
                    return Redirect(Request.Path);
                }
            }

            var downloadId = this.downloads.CreateFile(
                download.FileName,
                download.Description,
                fileArray,
                userId
                );

            TempData[MessageConstants.SuccessMessage] = "Успешно добавихте PDF файл.";
            return Redirect($"../../Download/All");
        }

        public async Task<FileResult> Download(Guid id)
        {
            var file = await downloads.GetFile(id);
            return File(file.FilePDF, "application/pdf");
        }

        [Authorize(Roles = UserConstants.Administrator)]
        public IActionResult Edit(Guid id)
        {
            var userId = this.users.IdByUser(this.User.Id());

            if (userId == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var newsForm = this.downloads.EditViewData(id);

            return View(newsForm);
        }

        [HttpPost]
        [Authorize(Roles = UserConstants.Administrator)]
        public IActionResult Edit(Guid id, DownloadEditFormModel download)
        {

            var edited = this.downloads.Edit(
                id,
                download.FileName,
                download.Description
                );

            if (!edited)
            {
                return BadRequest();
            }

            TempData[MessageConstants.SuccessMessage] = "Информацията за файла беше успешно редактирана.";
            return RedirectToAction("All");
        }

        [Authorize(Roles = UserConstants.Administrator)]
        public IActionResult Delete(Guid id)
        {
            var userId = this.users.IdByUser(this.User.Id());

            if (userId == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var downloadForm = this.downloads.DeleteViewData(id);

            return View(downloadForm);
        }

        [HttpPost]
        [Authorize(Roles = UserConstants.Administrator)]
        public IActionResult Delete(Guid id, DownloadDeleteModel download)
        {

            var deleted = this.downloads.Delete(id);

            if (!deleted)
            {
                return BadRequest();
            }

            TempData[MessageConstants.SuccessMessage] = "Файлът беше успешно изтрит.";
            return RedirectToAction("All");
        }
    }
}

ElectricTransportBlog/Controllers/PublicationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using ElectricTransportBlog.Core.Constants;
using ElectricTransportBlog.Core.Contracts;
using ElectricTransportBlog.Core.Extensions;
using ElectricTransportBlog.Core.Models.Publication;
using ElectricTransportBlog.Core.Models.PublicationComments;

namespace ElectricTransportBlog.Controllers
{
    public class PublicationController : Controller
    {
        private readonly IPublicationService publication;
        private readonly IUserService users;
        private readonly IPublicationCommentsService comments;

        public PublicationController(IPublicationService news, IUserService users, IPublicationCommentsService comments)
        {
            this.publication = news;
            this.users = users;
            this.comments = comments;
        }

        public IActionResult All(int p = 1, int s = 10)
        {
            var latestPublication = this.publication.All(p, s);

            return View(latestPublication);
        }

        public IActionResult Details(Guid id)
        {
            if (id == Guid.Empty)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var publication = this.publication.Details(id);

            if (publication == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction("All");
            }

            return View(publication);
        }

        [Authorize(Roles = $"{UserConstants.Administrator},{UserConstants.Moderator}")]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = $"{UserConstants.Administrator},{UserConstants.Moderator}")]
        public async Task<IActionResult> AddAsync(PublicationAddFormModel publication)
        {
            var userId = this.users.IdByUser(this.User.Id());

            if (userId == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            byte[] fileArray = null;

            using (var memoryStream = new MemoryStream())
            {
                await publication.FileUpload.PhotoFile.CopyToAsync(memoryStream);

                string fileExt = Path.GetExtension(publication.FileUpload.PhotoFile.FileName.ToLower());

                if (fileExt == ".jpeg" || fileExt == ".jpg")
                {
                    // Upload the file if less than 2 MB
                    if (memoryStream.Length < 2097152)
                    {
                        fileArray = memoryStream.ToArray();
                    }
                    else
                    {
                        TempData[MessageConstants.ErrorMessage] = "Размерът на снимката е твърде голям! Моля качете снимка до 2MB!";
                        return Redirect(Request.Path);
                    }
                }
                else
                {
                    TempData[MessageConstants.ErrorMessage] = "Само .jpeg/.jpg файлове са разрешени!";
                    return Redirect(Request.Path);
                }
            }

            var publicationId = this.publication.CreatePublication(
                publication.Title,
                publication.Description,
                DateTime.Now,
                userId,
                fileArray,
                false);

            TempData[MessageConstants.SuccessMessage] = "Новината беше успешно добавена.";
            return RedirectToAction("All");
        }

        [Authorize(Roles = $"{UserConstants.Administrator},{UserConstants.Moderator}")]
        public IActionResult Edit(Guid id)
        {
            var userId = this.users.IdByUser(this.User.Id());

            if (userId == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var news = this.publication.Details(id);

            var newsForm = this.publication.EditViewData(news.Id);

            return View(newsForm);
        }

        [HttpPost]
        [Authorize(Roles = $"{UserConstants.Administrator},{UserConstants.Moderator}")]
        public async Task<IActionResult> EditAsync(Guid id, PublicationEditFormModel publication)
        {
            byte[] fileArray = null;

            if (publication.FileUpload != null)
            {

                using (var memoryStream = new MemoryStream())
                {
                    await publication.FileUpload.PhotoFile.CopyToAsync(memoryStream);

                    string fileExt = Path.GetExtension(publication.FileUpload.PhotoFile.FileName.ToLower());

                    if (fileExt == ".jpeg" || fileExt == ".jpg")
                    {
                        // Upload the file if less than 2 MB
                        if (memoryStream.Length < 2097152)
                        {
                            fileArray = memoryStream.ToArray();
                        }
                        else
                        {
                            TempData[MessageConstants.ErrorMessage] = "Размерът на снимката е твърде голям! Моля качете снимка до 2MB!";
                            return Redirect(Request.Path);
                        }
                    }
                    else
                    {
                        TempData[MessageConstants.ErrorMessage] = "Само .jpeg/.jpg файлове са разрешени!";
                        return Redirect(Request.Path);
                    }
                }
            }

            var edited = this.publication.Edit(
                id,
                publication.Title,
                publication.Description,
                fileArray);

            if (!edited)
            {
                return BadRequest();
            }

            TempData[MessageConstants.SuccessMessage] = "Новината беше успешно редактирана.";
            return Redirect($"../../Publication/Details/{id}");
        }

        [Authorize(Roles = $"{UserConstants.Administrator},{UserConstants.Moderator}")]
        public IActionResult Delete(Guid id)
        {
            var userId = this.users.IdByUser(this.User.Id());

            if (userId == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var news = this.publication.Details(id);

            var newsForm = this.publication.DeleteViewData(news.Id);

            return View(newsForm);
        }

        [HttpPost]
        [Authorize(Roles = $"{UserConstants.Administrator},{UserConstants.Moderator}")]
        public IActionResult Delete(Guid id, PublicationDeleteModel news)
        {

            var deleted = this.publication.Delete(id, true);

            if (!deleted)
            {
                return BadRequest();
            }

            TempData[MessageConstants.SuccessMessage] = "Новината беше успешно изтрита.";
            return RedirectToAction("All");
        }

        [HttpPost]
        [Authorize]
        public IActionResult Details(Guid id, CommentAddFormModel comment)
        {
            var userId = this.users.IdByUser(this.User.Id());

            if (userId == null)
            {
                TempData[MessageConstants.ErrorMessage] = "Възникна грешка!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var edited = this.comments.CreatePublicationComment(
                comment.Content,
                DateTime.Now,
                userId,
                id);

            TempData[MessageConstants.SuccessMessage] = "Успешно публикувахте коментар.";
            return Redirect(Request.Path);
        }
    }
}

ElectricTransportBlog/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using ElectricTransportBlog.Core.Constants

<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - Блог за електрически транспорт</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/css/adminlte.min.css">
    <link rel="stylesheet" href="~/plugins/toastr/toastr.css" asp-append-version="true">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">

    <script src="https://cdn.tiny.cloud/1/bu0lhgssvsbd8sv715jacrfalsk766uiuz5b156bemqwlsah/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script type="text/javascript"> tinymce.init({ selector: '#richtextarea' });
  </script>

    @await RenderSectionAsync("Head", false)
</head>
<body class="hold-transition sidebar-collapse layout-top-nav">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
            <div class="container">
                <a href="/" class="navbar-brand">
                    <img src="~/img/TTLogo.png" alt="Trolley Logo" class="brand-image" style="opacity: .8">
                    <span class="brand-text font-weight-light">Блог за ел. транспорт</span>
                </a>

                <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse order-3" id="navbarCollapse">
                    <!-- Left navbar links -->
                    <ul class="navbar-nav">
                        @if (this.User.IsInRole(UserConstants.Administrator) || this.User.IsInRole(UserConstants.Moderator))
                        {
                            <li class="nav-item">
                                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Publication" asp-action="All">Публикации</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TransportNetwork" asp-action="All">Електрическият транспорт в България</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Download" asp-action="All">За изтегляне</a>
                        </li>
                    </ul>
                </div>

                <!-- Right navbar links -->
                <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
                    <li class="nav-item">
                        <partial name="_LoginPartial" />
                    </li>

                </ul>
            </div>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <partial name="_SidebarMenu" />

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0">@ViewData["Title"]</h1>
                        </div><!-- /.col -->
                        @*<div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="#">Layout</a></li>
                            </ol>
                        </div><!-- /.col -->*@
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <div class="content">
                <div class="container">
                    @RenderBody()
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="float-right d-none d-sm-inline">
                Anything you want
            </div>
            <!-- Default to the left -->
            <strong>Copyright &copy; @DateTime.UtcNow.Year <a href="/">Блог за електрически градски транспорт. </a> </strong>Всички права са запазени.
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/adminlte.min.js"></script>
    <script src="~/plugins/toastr/toastr.min.js"></script>
    <partial name="_UserMessages" />
    @await RenderSectionAsync("Scripts", false)
</body>
</html>

ElectricTransportBlog/Views/Shared/_LayoutOld.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PublicTransport</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PublicTransport.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PublicTransport</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PublicTransport - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ElectricTransportBlog/Views/Shared/_SidebarMenu.cshtml
@using ElectricTransportBlog.Core.Constants

@if (this.User.IsInRole(UserConstants.Administrator))
{
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
    <a href="/" class="brand-link">
            <img src="~/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
            <span class="brand-text font-weight-light">Админ панел</span>
        </a>

        <!-- Sidebar -->
    <div class="sidebar">
            <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="info">
                    <a class="d-block text-center">Добре дошли в <br>администраторския панел, <br><b>@this.User.Identity?.Name</b></a>
                </div>
            </div>

            <!-- Sidebar Menu -->
        <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <!-- Add icons to the links using the .nav-icon class
                         with font-awesome or any other icon font library -->
                <li class="nav-header">Опции</li>
                    <li class="nav-item">
                        <a asp-area="" asp-controller="Publication" asp-action="Add" class="nav-link">
                            <i class="nav-icon far fa-calendar-alt"></i>
                            <p>
                                Добави публикация
                                <span class="badge badge-info right"></span>
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="" asp-controller="TransportNetwork" asp-action="Add" class="nav-link">
                            <i class="nav-icon fas fa-bus"></i>
                            <p>
                                Добави транспортна мрежа
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="" asp-controller="Download" asp-action="AddPDF" class="nav-link">
                            <i class="nav-icon fas fa-file-pdf"></i>
                            <p>
                                Добавяне на PDF
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="RoleManage" asp-controller="UserRole" asp-action="ManageUsers" class="nav-link">
                            <i class="nav-icon fas fa-user-cog"></i>
                            <p>
                                Управление на роли
                            </p>
                        </a>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
    </div>
        <!-- /.sidebar -->
</aside>
}
else if (this.User.IsInRole(UserConstants.Moderator))
{
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
    <a href="/" class="brand-link">
            <img src="~/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
            <span class="brand-text font-weight-light">Модератор панел</span>
        </a>

        <!-- Sidebar -->
    <div class="sidebar">
            <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="info">
                    <a class="d-block text-center">Добре дошли в <br>модераторския панел, <br><b>@this.User.Identity?.Name</b></a>
                </div>
            </div>

            <!-- Sidebar Menu -->
        <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <!-- Add icons to the links using the .nav-icon class
                         with font-awesome or any other icon font library -->
                <li class="nav-header">Опции</li>
                    <li class="nav-item">
                        <a asp-area="" asp-controller="Publication" asp-action="Add" class="nav-link">
                            <i class="nav-icon far fa-calendar-alt"></i>
                            <p>
                                Добави новина
                                <span class="badge badge-info right"></span>
                            </p>
                        </a>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
    </div>
        <!-- /.sidebar -->
</aside>
}

ElectricTransportBlog/Views/Shared/_UserMessages.cshtml
@using ElectricTransportBlog.Core.Constants

@if (TempData[MessageConstants.ErrorMessage] != null)
{
    <script>
        $(function() {
            toastr.error('@TempData[MessageConstants.ErrorMessage]?.ToString()')
        })
    </script>
}

@if (TempData[MessageConstants.WarningMessage] != null)
{
    <script>
        $(function() {
            toastr.warning('@TempData[MessageConstants.WarningMessage]?.ToString()')
        })
    </script>
}

@if (TempData[MessageConstants.InformationMessage] != null)
{
    <script>
        $(function() {
            toastr.info('@TempData[MessageConstants.InformationMessage]?.ToString()')
        })
    </script>
}

@if (TempData[MessageConstants.SuccessMessage] != null)
{
    <script>
        $(function() {
            toastr.success('@TempData[MessageConstants.SuccessMessage]?.ToString()')
        })
    </script>
}

<script>
        toastr.options.timeout = 3000;
        toastr.options.positionClass = 'toast-top-right';
</script>